workspace:
  base: /go

pipeline:
  test:
    image: golang:1.7
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    repo: plugins/drone-niftycloud-object-storage
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: NIFTY Cloud ObjectStorage
  desc: Publish files and artifacts to NIFTY Cloud
  type: publish
  image: plugins/niftycloud-object-storage
  labels:
    - publish
    - artifacts
    - niftycloud
    - storage
