FROM armhfbuild/alpine:3.4

RUN apk update && \
  apk add \
    ca-certificates \
    mailcap && \
  rm -rf /var/cache/apk/*

ADD drone-niftycloud-object-storage /bin/
ENTRYPOINT ["/bin/drone-niftycloud-object-storage"]
